### ISSUE TITLE
Dynamic Loader implementation

### ISSUE THREAD

**Issue by george-dilthey** [erdalcay/onetag-gtm-template#1]
Hello,

It looks like this template is using the static loader. Any chance it will be updated to use the dynamic loader? https://support.criteo.com/s/article?article=Switching-to-the-dynamic-loader-for-Criteo-OneTag&language=en_US

**Comment by erdalcay** [comment]
Hi George,

This template is more than 2 years old and I have never updated it ever since. I don't have plans to update it either.

I am not a Criteo employee anymore but as far as I remember one of the teams at the company was working on a much more up-to-date version of the template back then when I was there. Can you check Criteo's documentation and see if they have an official tag template for GTM?

Cheers.

**Comment by george-dilthey** [comment]
Hey Erdal,

Thanks so much. I had thought this was the official template, but I'll reach out to Criteo support to ask.

Cheers,
George
